### PR TITLE
7 vote on a review

### PR DESCRIPTION
**Pull request by TomReece1**
Bug: When I invoke setReview with a review object with a new votes number, it's also reassigning the created_date. I think it's a problem with the API call, the patch request is changing the data in the database for created_date when it should only change the votes number.

I've just removed the created_date from the review display for now and i'm happy to continue with new tickets and fix the API later. I could probably get around it in the front end but seems correct to fix in back end.

I'll also add the bug to the issues log.

### CODE REVIEW

**Review by Angaca — CHANGES_REQUESTED** [review]
Agree with your reading of the bug! In terms of front-end functionality, I expect to only be able to vote OR downvote once and eventually change my mind and do the opposite after I have removed my previous preference (and I shouldn't be able to vote for things I (the logged user) have done)

**Comment by TomReece1** [comment]
Agree.
I'll add this now "vote OR downvote once and eventually change my mind and do the opposite after I have removed my previous preference".
But no core ticket says to have users, I'll do it but it sounds like it could be a separate ticket+pull request?
I'll respond again when the first part is done and reassess then.

**Comment by TomReece1** [comment]
Can I get another review on the added functionality to the upvote/downvote buttons, and advise on whether I should add users as part of this ticket, or as a new ticket after this one?

**Review by Angaca — APPROVED** [review]
Good to go! The user thing is just something to keep at mind for the future :)

**Pull request merged**
